### ISSUE TITLE
oauth2client.clientsecrets.InvalidClientSecretsError: Invalid file format

### ISSUE THREAD

**Issue by jnsmkl** [CsabaSzabo/ingatlan-kereso#1]
Hi, i faced w the bellow issue, do you have any idea what is the problem?

Python 3.6.0

Janoss-MBP:ingatlan-kereso janosmikle$ python3 ingatlan-kereso.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 86, in _validate_clientsecrets
    (client_type, client_info), = clientsecrets_dict.items()
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ingatlan-kereso.py", line 443, in <module>
    main()
  File "ingatlan-kereso.py", line 368, in main
    gc = pygsheets.authorize(outh_file='client_secret.json')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygsheets/client.py", line 547, in authorize
    outh_nonlocal=outh_nonlocal)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygsheets/client.py", line 505, in get_outh_credentials
    flow = client.flow_from_clientsecrets(client_secret_file, SCOPES)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 126, in _loadfile
    return _validate_clientsecrets(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 89, in _validate_clientsecrets
    _INVALID_FILE_FORMAT_MSG + ' '
oauth2client.clientsecrets.InvalidClientSecretsError: Invalid file format. See https://developers.google.com/api-client-library/python/guide/aaa_client_secrets Expected a JSON object with a single property for a "web" or "installed" application

cat client_secret.json
{
  "type": "service_account",
  "project_id": "ingatlan-kereso",
  "private_key_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "private_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "client_email": "ingatlan-kereso-4434324225@ingatlan-kereso.iam.gserviceaccount.com",
  "client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/ingatlan-kereso-4434324225%40ingatlan-kereso.iam.gserviceaccount.com"
}

Many thnx!
J

**Comment by whatareyoutalkingaboutyousoundinsane** [comment]
I have a similar error message when trying to authorize. My code is only the following:
```
import pygsheets
gc = pygsheets.authorize(outh_file='/Users/Myusername/Projects/Python projects/google sheets test/client_secret.json')
```
Which returns that same error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 86, in _validate_clientsecrets
    (client_type, client_info), = clientsecrets_dict.items()
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Myusername/Projects/Python projects/google sheets test/test that baby action.py", line 3, in <module>
    gc = pygsheets.authorize(outh_file='/Users/Myusername/Projects/Python projects/google sheets test/client_secret.json')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygsheets/client.py", line 596, in authorize
    outh_nonlocal=outh_nonlocal)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygsheets/client.py", line 555, in get_outh_credentials
    flow = client.flow_from_clientsecrets(client_secret_file, SCOPES)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 126, in _loadfile
    return _validate_clientsecrets(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 89, in _validate_clientsecrets
    _INVALID_FILE_FORMAT_MSG + ' '
oauth2client.clientsecrets.InvalidClientSecretsError: Invalid file format. See https://developers.google.com/api-client-library/python/guide/aaa_client_secrets Expected a JSON object with a single property for a "web" or "installed" application
```
And, here's the json in case you were wondering:
```
{
  "type": "service_account",
  "project_id": "trusty-cacao-201620",
  "private_key_id": "ada3…3e4",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEv…aeny+rw\n-----END PRIVATE KEY-----\n",
  "client_email": "myname@trusty-cacao-201620.iam.gserviceaccount.com",
  "client_id": "109696671903923437286",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/myname%40trusty-cacao-201620.iam.gserviceaccount.com"
}
```
To be clear, this is what I've done: Followed the ['how to authorize' page of the documentation](https://pygsheets.readthedocs.io/en/latest/authorizing.html) exactly, for Signed Credentials. Google Sheets and Drive APIs are both enabled on my Google Developers Console. I'm using the full path to the json file it gave me, after renaming the file to client_secret.json and putting it in the folder for this project.

Help? I feel like this _could_ be user error as I'm very new to Python and obviously this library & API… But at the same time, I _am_ following the directions on the documentation page precisely. Thanks!
